camel:
    springboot:
        main-run-controller: true
file:
    path:
        input: '/in/'
        input.extension: 'dat'
        output: '/out/'
logging:
    level:
        root: INFO
record:
    delimiter: 'รง'
    id:
        salesman: '001'
        customer: '002'
        sales: '003'
